version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sa@12345
    ports:
      - "1433:1433"
    networks:
      - microservice-network
    volumes:
      - mssql_data:/var/opt/mssql/data

  productservice:
    container_name: product-service
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProductServiceDb;User Id=sa;Password=Sa@12345;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - microservice-network

  orderservice:
    container_name: order-service
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderServiceDb;User Id=sa;Password=Sa@12345;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - microservice-network

volumes:
  mssql_data:
  
networks:
  microservice-network:
    driver: bridge
