<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\bak\BuildingBlocks.Contracts\Events\IntegrationEvent.cs" Link="Events\IntegrationEvent.cs" />
    <Compile Include="..\bak\BuildingBlocks.Contracts\Events\OrderCreatedEvent.cs" Link="Events\OrderCreatedEvent.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
  </ItemGroup>

</Project>
